modules:
  - type: rpm-ostree
    install:
      - byobu
#      - guake
      - gamemode.i686
      - gamescope
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-dash-to-panel
      - gnome-shell-extension-gamemode
      - gnome-shell-extension-gsconnect
      - nautilus-gsconnect
#      - gnome-shell-extension-pop-shell
      - gnome-shell-extension-system-monitor-applet
      - gnome-shell-extension-workspace-indicator
      - mangohud
      # Nextcloud also requires the script nextcloud-vfs.sh, called from the file common-scripts.yml
      - nextcloud-client-devel
      - nextcloud-client-nautilus
      - simple-scan
      - syncthing
    remove:
      - gnome-shell-extension-background-logo
      # Firefox is not installed on bazzite.
      - firefox
      - firefox-langpacks

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles # add "!include /usr/share/ublue-os/just/100-bling.just" in your custom.just (added by default) or local justfile
      - ublue-os-wallpapers
      - ublue-update # https://github.com/ublue-os/ublue-update

  - type: yafti

## Upstream:

#  - type: bling # configure what to pull in from ublue-os/bling
#    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
#    install:
      # - micro
      # - starship
      # - nix-installer # shell shortcuts for determinate system's nix installers
      # - 1password # install 1Password (stable) and `op` CLI tool
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm
      # - gnome-vrr # enables gnome-vrr for your image
      # - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
      # - laptop # installs TLP and configures your system for laptop usage
      # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section

#  - type: yafti
      # if included, yafti and it's dependencies (pip & libadwaita)
      #  will be installed and set up
#    custom-flatpaks:
      # this section is optional
#      - (Laptop) TLP-UI: com.github.d4nj1.tlpui
#      - GNOME Boxes: org.gnome.Boxes
#      - GNOME Dconf Editor: ca.desrt.dconf-editor
#      - Blanket: com.rafaelmardojai.Blanket
#      - Emby Theater: media.emby.EmbyTheater
#      - Gear Lever: it.mijorus.gearlever
#      - GitHub Desktop: io.github.shiftey.Desktop
#      - Joplin: net.cozic.joplin_desktop
#      - LibreOffice: org.libreoffice.LibreOffice
#      - Microsoft Edge: com.microsoft.Edge
#      - Mission Center: io.missioncenter.MissionCenter
#      - NewsFlash: io.gitlab.news_flash.NewsFlash
#      - Trilium Notes: com.github.zadam.trilium
#      - Ungoogled Chromium: com.github.Eloston.UngoogledChromium
      # - Celluloid: io.github.celluloid_player.Celluloid
      # - Krita: org.kde.krita
