modules:
  - type: rpm-ostree
    install:
      - nextcloud-client-devel # On Fedora, nextcloud-client does not contain the libraries for virtual files support. Flatpak does not work with virtual files. AppImage does not integrate with Nautilus.
      - nextcloud-client-nautilus
      - gnome-shell-extension-pop-shell
      - gnome-shell-extension-gsconnect
      - nautilus-gsconnect
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dash-to-panel
      - gnome-shell-extension-workspace-indicator
      - syncthing
    remove:
      - gnome-shell-extension-background-logo
