name: build-others
on:
  schedule:
    - cron: "30 6 1,15 * *" # Set in UTC: 6:30 AM on 1st and 15th day of each month.

  push:
    paths:
      - recipes/image-budgie.yml
      - recipes/image-cosmic.yml
#      - .github/workflows/build-others.yml
#      - files/scripts/image_name-v.sh
#      - files/scripts/image_name-s.sh
#      - files/theme-v/**
#      - files/theme-s/**
#      - files/system/**
#      - files/laptop/**

  workflow_dispatch: # allow manually triggering builds

jobs:
  bluebuild:
    name: Budgie Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - image-budgie.yml
          - image-cosmic.yml
    steps:
       # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.9
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          # enabled by default, disable if your image is small and you want faster builds      
          maximize_build_space: false
          
          # Optional flags
          use_unstable_cli: false
          rechunk: true
#          squash: true
