name: Clean Workflow Logs

on:
  schedule:
    - cron: "30 1 * * 1" 

  workflow_dispatch:

permissions:
  actions: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v7
        with:
          runs_older_than: 30
          runs_to_keep: 10
